version: '3.9'
services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    volumes: 
      - ./frontend:/app-frontend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
    networks:
      - net
  backend:
    build: ./backend
    restart: always
    ports:
      - "3001:3001"
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app-backend
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/ProjectTest
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
    networks:
      - net
      
  mongodb:
    container_name: project_test_db
    image: mongo:5.0.7
    restart: always
    networks:
      - net
    ports:
      - 27017:27017


networks:
  net:
    driver: bridge
